#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \setmainfont{宋体}
#+STARTUP: latexpreview
* Blog Topics
** 读书(novel)
 <2022-04-30 Sat 10:24>
 
    - 复旦骆玉明
     * 《陶庵梦忆》--张岱
** 浮生六记
 <2022-04-30 Sat 10:24>
 
 于破书残画反极珍惜。书之残缺不全者，必搜集分门，汇订
 成帙，统名之曰“断简残编”；字画之破损者，必觅故纸粘补
 成幅，有破缺处，倩予全好而卷之，名曰“弃余集赏”。于女

红中馈之暇，终日琐琐，不惮煩倦。芸于破笥懒卷中，偶获

片纸可观者，如得异宝。
** 叶嘉莹评苏东坡 （bilibili：北京大学出版社官方）
 <2022-04-30 Sat 10:23>
    - 柳永
     诗歌很丰富
   - 晏殊
     仕途平顺
** 浮生六记-沈复
 <2022-04-30 Sat 10:22>
 “《国策》、《南华》取其灵快；匡衡、刘向取其雅健；史迁

 、班固取其博大；昌黎取其浑；柳州取其峭；庐陵取其宕；

 三苏取其辩，他若贾董策对，庾、徐骈体，陆贽奏议，取资

 者不能尽举，在人之慧心领会耳。”

   - 国策：指《战国策》。为先秦时期的著名史学著作。南华：

     指《庄子》。道教奉其为《南华经》，古称。匡衡、刘向：

     俱为西汉人。都是著名学者。匡衡以善解《诗经》闻名。刘

     向著有《别录》。史迁：司马迁。西汉史学家。因其著有《

     史记》，故称史迁。班固：西汉史学家。著有《汉书》。昌

     黎：唐代文学家韩愈，昌黎为其字。柳州：唐代文学家柳宗

     元。因其曾任柳州司马，故称。庐陵：宋代文学家欧阳修。
     因其出生于庐陵吉水，故称。三苏：指宋代文学家苏洵、苏
     轼、苏辙。贾、董：分别指汉代的文学家贾谊和经济学家董
     仲舒。庾、徐：分别指南北朝时期的文学家愈信和徐陵。陆

   贽：唐代作家，长于政治论。

     
    - 叶嘉莹
      文学家，对欧阳修、苏轼很有了解

      
* bingxing
** 雨季不再来 三毛
 <2022-04-30 Sat 11:25>

 有一天，哑巴神秘兮兮地招手唤我，我跑上去，掌心里一打

 开,里面是一只金戒指，躺在几乎裂成地图一般的粗手掌里。

 1. 坐公共汽车好像是三毛钱  电影要六块
 2. 秋天的落叶如同舞倦的蝴蝶

流去的种种，化为一群一群蝴蝶，虽然早已明白了，世上的生命，

大半朝生暮死，而蝴蝶也是朝生暮死的东西，可是依然为着它的

色彩目眩神迷，觉着生命所有的神秘与极美已在蜕变中竟彰显了

全部的答案。而许多彩色的蝶，正在纱帽山的谷底飞去又飞来。

就这样，我一年又一年地活了下来，只为了再生时蝴蝶的颜色。

| 掮 | RYNE           | 骊 | $l\acute{i}$   |
| 哗 | $hu\bar{a}$    | 鎯 | $l\acute{a}ng$ |
| 埂 | $g\check{e}ng$ | 涟 | $li\acute{a}n$ |
| 搁 | $g\bar{e}$     | 漪 | $y\bar{i}$     |
| 懋 | SCBN           | 嗳 | KEPC           |
| 鹤 | PWY            | 誊 | UDYF           |
| 踉 | KHYE           | 跄 | KHWB           |
| 捩 | RYND           | 墀 | FNI            |
| 町 | LSH            | 吔 | KBN            |
| 恹 | NDDY           |    |                |
  

姗： 不知道在哪部电影里听过这句话，人生岁月尔尔，在

平淡中能寻取几丝欢乐，半段回忆，也是可调遣你半生的了。

当时我的感受还不止此，有多少人是需要被慰藉的，而又有

多少人是为生活奔波而被现实的担子压下来的，生活实在不

易，而人又要为这些事情劳苦终日，终年，甚至终其一生的

岁月......我很难回忆近几个月的种种感觉，就好像在根

本不属于自己生根......想当年的狂热和所谓好气质的自

傲都被现实洗刷殆尽了......一直想写信给你，我曾一再

地想过，也许台湾的种种都只能属于我从前的梦了，就像

你在小时候会一只纸船、一片落叶，所发出的绮梦一样......

也许我要否定那些从前被我珍惜的事物和记忆了......

这不是对你个人如此，而是对一切都改变了......

我一直地怀念你。

* haijin
** 看火影
 <2022-05-08 Sun 18:09>

 博人
* author
** 希大多
 <2022-05-08 Sun 18:11>

 人要学会孤独
